numero = input("Digite um número para ver sua tabuada: ")
print(f"Tabuada do {numero}:")
print(f"{numero} x 1 = {int(numero) * 1}")
print(f"{numero} x 2 = {int(numero) * 2}")
print(f"{numero} x 3 = {int(numero) * 3}")
print(f"{numero} x 4 = {int(numero) * 4}")
print(f"{numero} x 5 = {int(numero) * 5}")
print(f"{numero} x 6 = {int(numero) * 6}")
print(f"{numero} x 7 = {int(numero) * 7}")
print(f"{numero} x 8 = {int(numero) * 8}")
print(f"{numero} x 9 = {int(numero) * 9}")
print(f"{numero} x 10 = {int(numero) * 10}")